version: '2'
services:
  ariba:
    build: ../ariba
  mlst:
    build: ../mlst
  mlst_check:
    build: ../mlst_check 
  most:
    build: ../most
  spades:
    build: ../spades
  srst2:
    build: ../srst2
  stringmlst:
    build: ../stringmlst
